services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wayzi-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  pgdata: